---

# Schedule regular scans via crontab
# https://learn.microsoft.com/en-us/defender-endpoint/schedule-antivirus-scan-crontab

- name: Add daily quick scan
  ansible.builtin.cron:
    name: Microsoft Defender Daily Quick Scan
    hour: "{{ 5 | random(seed=inventory_hostname) }}"
    minute: "{{ range(0, 60) | random(seed=inventory_hostname) }}"
    job: /usr/bin/pgrep -f "mdatp scan" > /dev/null || /usr/bin/mdatp scan quick > /dev/null 2>&1

- name: Add weekly Custom Scan
  ansible.builtin.cron:
    name: Microsoft Defender Weekly Custom Scan
    hour: "{{ 3 | random(seed=inventory_hostname) }}"
    minute: "{{ range(0, 60) | random(seed=inventory_hostname) }}"
    weekday: "SUN"
    job: "/usr/bin/pgrep -f 'mdatp scan' > /dev/null || ( /usr/bin/mdatp scan custom --path /docker > /dev/null 2>&1 && /usr/bin/mdatp scan custom --path /var/lib/docker > /dev/null 2>&1 )"
