---

- name: Install Requirements
  ansible.builtin.apt:
    name: unzip,gpg
    update_cache: true

- name: Deploy the Onboarding Information
  ansible.builtin.import_tasks: onboarding_setup.yml

- name: Add the apt repository
  ansible.builtin.import_tasks: add_apt_repo.yml

- name: Install MDATP
  ansible.builtin.apt:
    name: mdatp
    state: latest
    update_cache: true

- name: Enable MDE with passive mode disabled and Real-Time Protection enabled
  ansible.builtin.command: /usr/bin/mdatp threat policy set --type potentially_unwanted_application --action block
