---

- name: Install Requirements
  ansible.builtin.apt:
    name: unzip,gpg
    update_cache: true

# https://m365admin.handsontek.net/microsoft-defender-endpoint-linux-removing-netfilter-dependency/
- name: Remove mde-netfilter if installed
  ansible.builtin.apt:
    name: mde-netfilter
    state: absent

- name: Deploy the Onboarding Information
  ansible.builtin.import_tasks: onboarding_setup.yml

- name: Add the apt repository
  ansible.builtin.import_tasks: add_apt_repo.yml

- name: Install MDATP
  ansible.builtin.apt:
    name: mdatp
    state: latest
    update_cache: true

- name: Add cron for regular scans
  ansible.builtin.import_tasks: cron_setup.yml

- name: Check current MDE policy
  ansible.builtin.command: /usr/bin/mdatp threat policy list
  register: mde_policy

- name: Enable blocking of Potentially Unwanted Applications (PUA) if not already set
  ansible.builtin.command: /usr/bin/mdatp threat policy set --type potentially_unwanted_application --action block
  when: "'potentially_unwanted_application' in mde_policy.stdout and 'block' not in mde_policy.stdout"
