---

- name: Install Requirements
  ansible.builtin.apt:
    name: unzip,gpg
    update_cache: true

- name: Deploy the Onboarding Information
  import_task: onboarding_setup.yml

- name: Add the apt repository
  import_task: add_apt_repo.yml

- name: Install MDATP
  ansible.builtin.apt:
    name: mdatp
    state: latest
    update_cache: true
